config/routes.rb
Rails.application.routes.draw do

  resources :posts do 
    resources :comments, only: [:create, :destroy]
    resources :notifications
  end
  resources :profiles
  devise_for :users
  root "static_pages#home"

  resources :rooms
  resources :messages




end

app/models/profile.rb
class Profile < ApplicationRecord
	belongs_to :user
	validates :full_name, presence: true
	validates :birthday, presence: true
	validates :phone, presence: true
	validates :address, presence: true
	validates :intersts, presence: true
	validates :user_id, presence: true

	has_one_attached :header_image
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: %i[ show edit update destroy ]

  # GET /profiles or /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1 or /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = current_user.build_profile
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles or /profiles.json
  def create
    @profile = current_user.build_profile(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: "Profile was successfully created." }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1 or /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: "Profile was successfully updated." }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1 or /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: "Profile was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def profile_params
      params.require(:profile).permit(:full_name, :birthday, :phone, :address, :intersts, :header_image)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_avt.html.erb
  <% if @profile.header_image.present? %>
    <%= image_tag(@profile.header_image, width: '400px', id: "avt_img") %>
  <% end %>
  &nbsp;

app/views/profiles/_form.html.erb
<%= form_with(model: profile) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
        <% profile.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :Image %>
    <%= form.file_field :header_image, class: 'image-control' %>
    <br>
    <br>
    <% if profile.header_image.present? %>
      <%= image_tag(profile.header_image, size: "400px") %>
    <% end %>
  </div>

  <div class="field form-group">
    <%= form.label :full_name %>
    <%= form.text_field :full_name, class:"form-control",placeholder:"Full name" %>
  </div>
<br>
  <div class="field form-group">
    <%= form.label :birthday %>
    <%= form.date_select :birthday, {order: [:day, :month, :year], prompt: { day: 'Select day', month: 'Select month', year: 'Select year' }, start_year: Date.today.year , end_year: Date.today.year - 100}, {required: true} %>
  </div>
<br>
  <div class="field form-group">
    <%= form.label :phone %>
    <%= form.number_field :phone, class:"form-control",placeholder:"Phone" %>
  </div>
<br>
  <div class="field form-group">
    <%= form.label :address %>
    <%= form.text_field :address, class:"form-control",placeholder:"Address" %>
  </div>
<br>
  <div class="field form-group">
    <%= form.label :intersts %>
    <%= form.text_field :intersts, class:"form-control",placeholder:"Interests" %>
  </div>
<br>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/profiles/_title.html.erb
<p>
  <strong>Full name:</strong>
  
</p>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>

<br>

<%= link_to 'Back', @profile %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Full name</th>
      <th>Birthday</th>
      <th>Phone</th>
      <th>Address</th>
      <th>Interests</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.full_name %></td>
        <td><%= profile.birthday %></td>
        <td><%= profile.phone %></td>
        <td><%= profile.address %></td>
        <td><%= profile.intersts %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<br>
<br>
<br>
<p id="notice"><%= notice %></p>
<strong>Avatar:</strong>
<span >
  <% if @profile.header_image.present? %>
    <%= image_tag(@profile.header_image, size:"200x200", id: "avt_img") %>
  <% end %>
  &nbsp;
</span>
<p>
  <strong>Full name:</strong>
  <%= @profile.full_name %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @profile.birthday %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @profile.phone %>
</p>

<p>
  <strong>Address:</strong>
  <%= @profile.address %>
</p>

<p>
  <strong>Interests:</strong>
  <%= @profile.intersts %>
</p>
  
<p class="edit_prf"><%= link_to 'Edit', edit_profile_path(@profile), id: "link_edit" %> </p>
<!-- |
<%= link_to 'Back', profiles_path %> -->