config/routes.rb
Rails.application.routes.draw do

  resources :posts do 
    resources :comments, only: [:create, :destroy]
    resources :notifications
  end
  resources :profiles
  devise_for :users
  root "static_pages#home"

  resources :rooms
  resources :messages




end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_one_attached :header_image
  has_many :notifications, as: :notificationable
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [ :edit, :update, :destroy ]

  # GET /posts or /posts.json
  def index
    @posts = current_user.posts
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post = Post.find(params[:id])
    @post.notifications.update_all checked: true
    @comment = Comment.new
    @comments = @post.comments
    # @post = current_user.posts.find(params[:id])
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.build(post_params)

      if @post.save
        redirect_to edit_post_path(@post)
      else
        render :new
      end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
      if @post.update(post_params)
        redirect_to edit_post_path(@post)
      else
        render :edit
      end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = current_user.posts.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content, :header_image)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :Title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>
<br>
  <div class="form-group">
    <%= form.label :Description %>
    <%= form.text_area :content, class: 'form-control' %>
  </div>
<br>
  <div class="form-group">
    <%= form.label :Image %>
    <%= form.file_field :header_image, class: 'image-control' %>
    <br>
    <br>
    <% if post.header_image.present? %>
      <%= image_tag(post.header_image, size:"60x60") %>
    <% end %>
  </div>
<br>
  <div class="actions">
    <%= form.submit class: 'btn-primary' %>
  </div>
<% end %>
<br>

app/views/posts/_post_information.html.erb
<br>
<p class="anh_test"><%= image_tag("2.jpg", size:"1600x450") %></p>
<div class="list_post">
<% Post.all.each do |post| %>
  <%= link_to post_path(post.id), class: 'text-decoration-none' do %>
    <div class="post_body">
      <div class="card-body">
        <table>
            <td>
                <% if post.header_image.present? %>
                    <%= image_tag(post.header_image, width: '400px') %>
                <% end %>
                &nbsp;
            </td>

            <td>
                <strong><p class="post_title" ><%= post.title %></p></strong>
                <!-- <h5 class="post_description"><%= post.content %></h5> -->
                <div class="post_description">
                    <% if post.content.length > 350 %>
                        <%= truncate(post.content, length: 350) %>...
                    <% else %>
                        <%= post.content %>
                    <% end %>
                <div>
            </td>
        </table>
      </div>
    </div>
  <% end %>
<% end %>
</div>

app/views/posts/edit.html.erb
<br>
<br>
<br>
<div class="row">
	<div class="col-md-3">

				<h4 class="card-title">Editing Post </h4>
				<%= render 'form', post: @post %>
				<%= button_to 'Delete', @post,  method: :delete, data: { confirm: 'Are you sure?' }%>

		
	</div>
	
</div>

app/views/posts/index.html.erb
<h4 class='d-flex justify-content-between'>
  <span>Posts</span>
  <%= link_to 'New Post', new_post_path, class: 'btn btn-primary' %>
  
</h4> 

<p id="notice"><%= notice %></p>


<%= render "post_information" %>
<br>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<br>
<br>
<br>
<p id="notice"><%= notice %></p>
<p>
  <% if @post.header_image.present? %>
  <%= image_tag(@post.header_image, width: '100%') %>
  <% end %>
</p>

<strong class="post_title">

  <%= @post.title %> <%= link_to 'Edit', edit_post_path(@post)%>  
  <br>
  <br>
</strong>



<p>
  <%= @post.content %>
</p>

<br>

<p>
  <strong>Blogger's email:</strong>
  <%= link_to "#{@post.user.email}",  @post.user.profile  %>
</p>

<%= render "comments/comment" %>