config/routes.rb
Rails.application.routes.draw do

  resources :posts do 
    resources :comments, only: [:create, :destroy]
    resources :notifications
  end
  resources :profiles
  devise_for :users
  root "static_pages#home"

  resources :rooms
  resources :messages




end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  has_one_attached :header_image
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  has_one_attached :header_image
  
end

app/models/notification.rb
class Notification < ApplicationRecord
  	belongs_to :user
  	belongs_to :notificationable, polymorphic: true

  	scope :num_not_check, ->{where(checked: false).count}
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_one_attached :header_image
  has_many :notifications, as: :notificationable
end

app/models/profile.rb
class Profile < ApplicationRecord
	belongs_to :user
	validates :full_name, presence: true
	validates :birthday, presence: true
	validates :phone, presence: true
	validates :address, presence: true
	validates :intersts, presence: true
	validates :user_id, presence: true

	has_one_attached :header_image
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages
  has_many :users, through: :messages
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :comments, dependent: :destroy
  has_many :messages
  validates :name, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :profile, dependent: :destroy
  has_many :notifications, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [ :edit, :update, :destroy ]

  # GET /posts or /posts.json
  def index
    @posts = current_user.posts
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post = Post.find(params[:id])
    @post.notifications.update_all checked: true
    @comment = Comment.new
    @comments = @post.comments
    # @post = current_user.posts.find(params[:id])
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.build(post_params)

      if @post.save
        redirect_to edit_post_path(@post)
      else
        render :new
      end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
      if @post.update(post_params)
        redirect_to edit_post_path(@post)
      else
        render :edit
      end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = current_user.posts.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content, :header_image)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!

  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    @rooms = Room.all
    render 'index'
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:name)
    end
end

app/controllers/user_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
  
    layout 'users'
    def index
      @users = User.all
    end
    def show
      @users = User.find_by_id(params[:id])
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
   <small>
   The <a href=" "> </a>
   by <a href=""> </a>
   </small>
   <nav>
      <ul>
         <li><%= link_to "About",
            '#' %></li>
         <li><%= link_to "Contact", '#' %></li>
         <li><a href=" ">News</a></li>
      </ul>
   </nav>
</footer>

app/views/layouts/_header.html.erb
  <header class="navbar navbar-fixed-top navbar-inverse">
         <div class="container">
            <%= link_to "Blog", root_path, id: "logo" %>
            <%= render "notifications/counter" %>
            <nav>
               <ul class="nav navbar-nav navbar-right">
                  <% if user_signed_in? %> 
                  <li class="room_chat_link" ><%= link_to 'Room chat', rooms_path, id: "link_header" %></li> 
                  <li class="new_post" ><%= link_to 'New Post', new_post_path, id: "link_header" %></li>   
                  <% if current_user.profile == nil %>
                     <li class="pprofile"><%= link_to "Create Profile", new_profile_path, id: "link_header" %></li>
                  <% else %>
                     <li class="pprofile"><%= link_to 'View Profile', current_user.profile, id: "link_header" %></li> 
                  <% end %>
                  <li class="help"><%= link_to "Help","#",id: "link_header" %>
                     <li><%= button_to "Sign Out", destroy_user_session_path, method: :delete, class:"signout" %>
                  <%else%>
                     <li class="signup"><%= link_to "Sign Up", new_user_registration_path, id: "link_header" %>
                     <li class="signin"><%= link_to "Sign In", user_session_path, id: "link_header" %>
                  <% end %>
               </ul>
            </nav>
         </div>
      </header>

app/views/layouts/application.html.erb
<!--  -->


<!DOCTYPE html>
<html>
  <head>
    <title>Chatapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </head>

  <body>
      <%= render 'layouts/header' %>
       <div class="container">
         <%= yield %>
         <%= render 'layouts/footer' %>
      </div>
  </body>
  <meta content='<%= user_signed_in? ? current_user.id : "" %>' name='user-id'/>
</html>